languageCode = "en"
languageName = "English"
weight = 1

title = "schmic.eu"
#copyright = "Copy, _right?_ :thinking_face:"

[params]
  isoCode = "en"
  displayName = "EN"
  rtl = false

  dateFormat = "2 January 2006"

  #mainSections = ["section1", "section2"]
  #description = "My awesome website"

[params.author]
  name = "Michael"
  image = "img/avatar.jpg"
  headline = "Married, dad of two, cyclist, gamer, certified machinetherapist.<br/><small>Plays with containers during the day.</small>"
  bio = ""
  links = [
  { github = "https://github.com/schmic" },
  { mastodon = "https://mastodon.social/@schmic" },
  #   { instagram = "https://instagram.com/username" },
  #   { keybase = "https://keybase.io/username" },
  ]

